baseURL = ""
relativeURLs = "True"
languageCode = 'en-us'
title = 'Ibrahim Sowunmi'
author = 'Ibrahim Sowunmi'
paginate = "10" # Number of posts per page
disableKinds = ["taxonomy","taxonomyTerm"]
theme = ["hugo-flex", "hugo-shortcode-gallery" ]
timeout = 1600000 
bookmarksJS = ["js/bookmarks.js"]


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "books"
    name = "Reading"
    url = "/books"
    weight = 20

  [[menu.main]]
    identifier = "bookmarks"
    name = "Bookmarks"
    url = "/bookmarks"
    weight = 20

  [[menu.main]]
    identifier = "art"
    name = "Art"
    url = "/art"
    weight = 20

  [[menu.main]]
    identifier = "photosets"
    name = "Photosets"
    url = "/photosets"
    weight = 20



[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
