[build]
  publish = "public"
  command = "hugo -b $URL"

[build.environment]
  HUGO_VERSION = "0.91.2"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404
